@include('partial.landing.header')
@include('partial.landing.navbar')
@include('partial.landing.vendor.banner')
@include('partial.landing.vendor.nav')
@yield('content')
@include('partial.landing.main_footer')
@include('partial.landing.footer')
